# Enable battery reporting on peripheral
CONFIG_ZMK_BATTERY_REPORTING=y

# peripheral info
CONFIG_ZMK_SPLIT_PERIPHERAL_HID_INDICATORS=y

CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

# sleep
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
